routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'MainController@index')->name('main');
Auth::routes(['verify' => true]);
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/accept-invitation/{uuid}', 'Auth\RegisterController@acceptInvitation');

// Auth routes
Route::group(['middleware' => 'auth'], function () {
    //Company Start
    Route::get('/company/start', 'Company\CompanyController@start')->name('company.start');
    Route::post('/company/start', 'Company\CompanyController@createCompany')->name('company.create');

    //Company
    Route::group(['middleware' => ['inCompany']], function () {
        Route::get('/company/general-info', 'Company\CompanyController@generalInfo')->name('company.general-info');
        Route::get('/company/settings', 'Company\CompanyController@settings')->name('company.settings');

        ////Profile
        //Profile | personal-info
        Route::get('/profile/personal-info', 'Profile\ProfileController@personalInfo')->name('profile.personal-info');
        Route::get('/profile/personal-info/edit', 'Profile\ProfileController@personalInfoEdit')->name('profile.personal-info.edit');
        Route::post('/profile/personal-info/edit', 'Profile\ProfileController@personalInfoUpdate')->name('profile.personal-info.update');
        //Profile | settings
        Route::get('/profile/settings', 'Profile\ProfileController@settings')->name('profile.settings');

        //Profile | settings | change password
        Route::get('/profile/settings/password_change', 'Profile\ProfileController@passwordChangeForm')->name('profile.password-change');
        Route::post('/profile/settings/password_change', 'Profile\ProfileController@passwordChangeStore')->name('profile.password-change-store');

        //Company Admin
        Route::get('/admin/users', 'Company\UsersController@index')->name('company-users.index');
        Route::get('/admin/users/add', 'Company\UsersController@addUserForm')->name('company-users.add');
        Route::post('/admin/users/add', 'Company\UsersController@inviteUser')->name('company-users.invite');
        Route::get('/admin/roles_permissions', 'Company\CompanyController@rolesPermissionsPage')->name('company.roles-permissions-page');
        Route::get('/admin/roles_permissions/add', 'Company\CompanyController@addRoleForm')->name('company.role.add');
        Route::post('/admin/roles_permissions/add', 'Company\CompanyController@storeRole')->name('company.role.store');
        Route::get('/admin/roles_permissions/edit/{role_id}', 'Company\CompanyController@editRole')->name('company.role.edit');
        Route::post('/admin/roles_permissions/update/{role_id}', 'Company\CompanyController@updateRole')->name('company.role.update');
        Route::get('/admin/company/user/edit/{user_id}', 'Company\UsersController@editUser')->name('admin-company-user.edit');
        Route::post('/admin/company/user/edit/{user_id}', 'Company\UsersController@updateUser')->name('admin-company-user.update');
        Route::post('/admin/user/delete', 'Company\UsersController@deleteUserFromCompany')->name('company-user.delete');

        //Tutorials module
        Route::get('/module/tutorials', 'Modules\Tutorials\TutorialsController@index')->name('module.tutorials.index');
        Route::get('/module/tutorials/view/{tutorial_id}', 'Modules\Tutorials\TutorialsController@view')->name('module.tutorials.view');
        Route::post('/module/tutorials/complete', 'Modules\Tutorials\TutorialsController@completeTutorial')->name('module.tutorials.complete');
        Route::get('/module/tutorials/admin', 'Modules\Tutorials\TutorialsController@manageTutorials')->name('module.tutorials.admin');
        Route::get('/module/tutorials/admin/add', 'Modules\Tutorials\TutorialsController@addTutorial')->name('module.tutorials.add');
        Route::post('/module/tutorials/admin/add', 'Modules\Tutorials\TutorialsController@storeTutorial')->name('module.tutorials.store');
        Route::get('/module/tutorials/admin/edit/{tutorial_id}', 'Modules\Tutorials\TutorialsController@edit')->name('module.tutorials.edit');
        Route::post('/module/tutorials/admin/edit/{tutorial_id}', 'Modules\Tutorials\TutorialsController@update')->name('module.tutorials.update');
        Route::post('/module/tutorials/admin/delete/{tutorial_id}', 'Modules\Tutorials\TutorialsController@delete')->name('module.tutorials.delete');
        Route::post('/module/tutorials/admin/change-order', 'Modules\Tutorials\TutorialsController@changeOrder')->name('module.tutorials.change-order');
        Route::get('/module/tutorials/statistics', 'Modules\Tutorials\TutorialsController@statisticsTutorial')->name('module.tutorials.statistics');
        Route::get('/module/tutorials/settings', 'Modules\Tutorials\TutorialsController@editTutorialSettings')->name('module.tutorials.settings.edit');
        Route::post('/module/tutorials/settings', 'Modules\Tutorials\TutorialsController@updateTutorialSettings')->name('module.tutorials.settings.update');
        Route::resource('/modules/tutorials/editor', 'Modules\Tutorials\CKEditorController');
        Route::post('/module/tutorials/editor/image_upload', 'Modules\Tutorials\CKEditorController@upload')->name('module.tutorials.editor.upload');

        Route::any('/elfinder-popup/{input_id}', '\Barryvdh\Elfinder\ElfinderController@showPopup')->name('elfinder.popup');
    });

    //Site Config=================
    Route::namespace('Admin')->prefix('admin')->group(function () {
        //Main Admin Config Page
        Route::resource('site-config', 'SiteConfigController');
        //User Management
        Route::resource('user-management', 'UserManagementController', ['parameters' => [
            'user-management' => 'user',
        ]]);
    });

      });

app/Http/Controllers/Admin/SiteConfigController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class SiteConfigController extends Controller {
    public function index(){
        return view('site-config.index')->with('authUser', Auth::user());
    }
}

resources/views/site-config/index.blade.php
@extends('layouts.admin')

@section('title', 'Site Config')

@section('content')
    <div class="container admin-container">
        <h2>Site Config</h2>

        @include('layouts.notifications')

    </div>
@endsection

resources/views/site-config/user-management.blade.php
@extends('layouts.admin')

@section('title', 'User Management')

@section('content')
    <div class="container bg-profile admin-container">
        <h2 class="mt-5 ml-3">User Management</h2>
        <div class="row">


            @include('layouts.notifications')

            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">{{ __('messages.Name') }}</th>
                            <th scope="col">{{ __('messages.Email') }}</th>
                            <th scope="col">{{ __('messages.Role') }}</th>
                            <th scope="col">{{ __('messages.Edit') }}</th>
                            <th scope="col">{{ __('messages.Delete') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{ $user->firstname }}</td>
                                <td>{{ ($user->email) }}</td>
                                <td>{{ $user->email }}</td>
                                <td>

                                    <form action="{{ route('user-management.edit', ['user' => $user->id]) }}"
                                          method="GET">
                                    @csrf
                                    <!-- <button class="btn btn-info btn-sm" title="{{ __('messages.Edit') }}">
                                        <i class="fas fa-edit"></i> {{ __('messages.Edit') }}
                                        </button> -->
                                        <button type="button"
                                                class="btn-men btn-men-inverse btn-men-custom waves-effect waves-light m-b-5">
                                            <i class="fas fa-edit mx-4 my-2"></i></button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('user-management.destroy', ['user' => $user->id]) }}"
                                          method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <!-- <button class="btn btn-danger btn-sm" title="{{ __('messages.Delete') }}" aria-hidden="true">
                                        <i class="fas fa-trash"></i> {{ __('messages.Delete') }}
                                        </button> -->
                                        <button type="button"
                                                class="btn-men btn-men-danger btn-men-custom waves-effect waves-light m-b-5"
                                                data-toggle="modal" data-target="#modal-info">
                                            <i class="fas fa-trash mx-4 my-2"></i></button>


                                        <!--Info Modal Template-->
                                        <div id="modal-info" class="modal modal-message modal-info fade modal fade modal-open" style="display: none;" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <i class="fas fa-user-times trash-user fa-3x mx-auto my-3"></i>
                                                    </div>
                                                    <div class="modal-title" id="exampleModalLongTitle">Are you sure you want to delete user <b>{{ $user->firstname }}</b> ?</div>


                                                    <div class="modal-footer mx-auto">
                                                        <button type="button" class="btn button-modal button-chancel" data-dismiss="modal">Cancel</button>
                                                        <button type="button" class="btn button-modal button-ok" data-dismiss="modal">OK</button>
                                                    </div>
                                                </div> <!-- / .modal-content -->
                                            </div> <!-- / .modal-dialog -->
                                        </div>
                                        <!--End Info Modal Templates-->

                                        <!-- Button trigger modal -->
                                    </form>
                                </td>
                            </tr>

                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection